import { AsyncLocalStorage } from 'node:async_hooks'
import pg from 'pg'
import { attachDatabasePool } from '@vercel/functions'

const { Pool, types } = pg
types.setTypeParser(20, value => Number(value))

const transactionContext = new AsyncLocalStorage()
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 5,
  idleTimeoutMillis: 5_000,
  connectionTimeoutMillis: 10_000,
})
attachDatabasePool(pool)

function postgresPlaceholders(sql) {
  let index = 0
  let quoted = false
  let result = ''
  for (let cursor = 0; cursor < sql.length; cursor++) {
    const character = sql[cursor]
    if (character === "'" && sql[cursor - 1] !== '\\') quoted = !quoted
    if (character === '?' && !quoted) result += `$${++index}`
    else result += character
  }
  return result
}

function query(sql, params = []) {
  const client = transactionContext.getStore()
  return (client ?? pool).query(postgresPlaceholders(sql), params)
}

function insertWithId(sql) {
  if (/\bRETURNING\b/i.test(sql)) return sql
  const table = sql.match(/^\s*INSERT\s+INTO\s+([a-z_]+)/i)?.[1]?.toLowerCase()
  return ['employees', 'requests', 'users'].includes(table) ? `${sql} RETURNING id` : sql
}

const database = {
  isPostgres: true,
  prepare(sql) {
    return {
      async get(...params) {
        const result = await query(sql, params)
        return result.rows[0]
      },
      async all(...params) {
        const result = await query(sql, params)
        return result.rows
      },
      async run(...params) {
        const statement = /^\s*INSERT\b/i.test(sql) ? insertWithId(sql) : sql
        const result = await query(statement, params)
        return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id }
      },
    }
  },
  transaction(callback) {
    return async (...args) => {
      const client = await pool.connect()
      try {
        await client.query('BEGIN')
        const result = await transactionContext.run(client, () => callback(...args))
        await client.query('COMMIT')
        return result
      } catch (error) {
        await client.query('ROLLBACK').catch(() => {})
        throw error
      } finally {
        client.release()
      }
    }
  },
  async backup(_label) {
    const tables = ['employees', 'shifts', 'shift_locks', 'locked_months', 'requests', 'app_settings']
    const snapshot = {}
    for (const table of tables) snapshot[table] = (await query(`SELECT * FROM ${table}`)).rows
    const created = await query('INSERT INTO app_backups (snapshot) VALUES ($1::jsonb) RETURNING id, created_at', [JSON.stringify(snapshot)])
    return `Neon 데이터 백업 ${created.rows[0].id} · ${created.rows[0].created_at}`
  },
}

export async function initializePostgres() {
  await query('ALTER TABLE employees ADD COLUMN IF NOT EXISTS produce_backup INTEGER NOT NULL DEFAULT 0')
  await query(`CREATE TABLE IF NOT EXISTS schedule_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month TEXT NOT NULL,
    username TEXT NOT NULL,
    action TEXT NOT NULL,
    snapshot TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`)
  await query(`CREATE TABLE IF NOT EXISTS app_backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`)
  await query('CREATE TABLE IF NOT EXISTS app_meta (meta_key TEXT PRIMARY KEY, meta_value BIGINT NOT NULL)')
  await query("INSERT INTO app_meta (meta_key, meta_value) VALUES ('data_revision', 0) ON CONFLICT(meta_key) DO NOTHING")
}

export default database
