import Database from 'better-sqlite3'
import pg from 'pg'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const { Pool } = pg
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = path.join(root, 'deployment', 'shift-planner.sqlite')
const databaseUrl = process.env.DATABASE_URL

if (!databaseUrl) throw new Error('DATABASE_URL 환경변수가 필요합니다.')

const source = new Database(sourcePath, { readonly: true })
const pool = new Pool({ connectionString: databaseUrl, max: 1 })

const schema = [
  `CREATE TABLE IF NOT EXISTS employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    employment_type TEXT NOT NULL DEFAULT '정규직',
    duty_type TEXT NOT NULL DEFAULT 'support',
    produce_qualified INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    notes TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    work_rules TEXT NOT NULL DEFAULT '{"allowedShifts":["open","close"],"offRules":[]}'
  )`,
  `CREATE TABLE IF NOT EXISTS shifts (
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    shift_date TEXT NOT NULL,
    code TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(employee_id, shift_date)
  )`,
  `CREATE TABLE IF NOT EXISTS shift_locks (
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    shift_date TEXT NOT NULL,
    code TEXT NOT NULL,
    PRIMARY KEY(employee_id, shift_date)
  )`,
  `CREATE TABLE IF NOT EXISTS locked_months (
    month TEXT PRIMARY KEY,
    locked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    request_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(employee_id, request_date)
  )`,
  'CREATE TABLE IF NOT EXISTS app_settings (setting_key TEXT PRIMARY KEY, setting_value TEXT NOT NULL)',
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'employee')),
    employee_id INTEGER UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
  )`,
]

const tables = {
  employees: ['id', 'name', 'employment_type', 'duty_type', 'produce_qualified', 'active', 'notes', 'sort_order', 'created_at', 'work_rules'],
  shifts: ['employee_id', 'shift_date', 'code', 'updated_at'],
  shift_locks: ['employee_id', 'shift_date', 'code'],
  locked_months: ['month', 'locked_at'],
  requests: ['id', 'employee_id', 'request_date', 'status', 'created_at'],
  app_settings: ['setting_key', 'setting_value'],
}

try {
  await pool.query('BEGIN')
  for (const statement of schema) await pool.query(statement)

  const existing = await pool.query(`
    SELECT (SELECT COUNT(*) FROM employees) AS employees,
           (SELECT COUNT(*) FROM shifts) AS shifts,
           (SELECT COUNT(*) FROM app_settings) AS settings
  `)
  if (Object.values(existing.rows[0]).some(value => Number(value) > 0)) {
    throw new Error('Neon DB에 기존 운영 데이터가 있습니다. 중복 덮어쓰기를 막기 위해 가져오기를 중단했습니다.')
  }

  for (const [table, columns] of Object.entries(tables)) {
    const rows = source.prepare(`SELECT ${columns.join(', ')} FROM ${table}`).all()
    for (const row of rows) {
      const values = columns.map(column => row[column])
      const placeholders = columns.map((_, index) => `$${index + 1}`).join(', ')
      await pool.query(`INSERT INTO ${table} (${columns.join(', ')}) VALUES (${placeholders})`, values)
    }
  }

  for (const table of ['employees', 'requests', 'users']) {
    await pool.query(`SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 1), EXISTS (SELECT 1 FROM ${table}))`)
  }
  await pool.query('COMMIT')

  const summary = await pool.query(`
    SELECT (SELECT COUNT(*) FROM employees) AS employees,
           (SELECT COUNT(*) FROM shifts) AS shifts,
           (SELECT COUNT(*) FROM shift_locks) AS shift_locks,
           (SELECT COUNT(*) FROM locked_months) AS locked_months,
           (SELECT COUNT(*) FROM requests) AS requests,
           (SELECT COUNT(*) FROM app_settings) AS settings,
           (SELECT COUNT(*) FROM users) AS users
  `)
  console.log(JSON.stringify(summary.rows[0]))
} catch (error) {
  await pool.query('ROLLBACK').catch(() => {})
  throw error
} finally {
  source.close()
  await pool.end()
}
