export type Role = 'admin' | 'employee'
export type User = { id: number; username: string; role: Role; employeeId: number | null; employeeName: string | null }
export type WorkRules = { allowedShifts: ('open' | 'close')[]; offRules: { weekday: number; occurrences: number[] }[] }
export type Validation = { issues: { date?: string; employeeId?: number; text: string }[]; pending: { date?: string; employeeId?: number; text: string }[]; warnings?: { date?: string; employeeId?: number; text: string }[]; stats: { employeeId: number; target: number; off: number; open: number; close: number; weekendWork?: number; longestConsecutive?: number }[] }
export type Employee = { id: number; name: string; employmentType?: '정규직' | '계약직'; dutyType?: 'functional' | 'support' | 'other'; produceQualified?: boolean; produceBackup?: boolean; active: number | boolean; notes: string; workRules?: WorkRules }
export type DutyType = NonNullable<Employee['dutyType']>
export type ShiftCode = 'open' | 'close' | 'full' | 'off'
export type Shift = { employeeId: number; employeeName: string; date: string; code: ShiftCode; employmentType?: Employee['employmentType']; start?: string | null; end?: string | null; locked?: boolean }
export type DayRequest = { id: number; employeeId: number; employeeName: string; date: string; status: 'pending' | 'approved' | 'rejected' }
export type Account = { id: number; username: string; role: Role; employeeId: number | null; employeeName: string | null }
export type Times = { start: string; end: string }
export type Operations = { minimumEmployeesForGeneration: number; weekdayTarget: number; weekendTarget: number; weekdayMinimum: number; weekendMinimum: number; staffingMode: 'combined' | 'employmentType'; weekdayRegularTarget: number; weekdayRegularMinimum: number; weekdayContractTarget: number; weekdayContractMinimum: number; weekendRegularTarget: number; weekendRegularMinimum: number; weekendContractTarget: number; weekendContractMinimum: number; functionalMinOnDuty: number; supportMaxOff: number; supportMaxRequestsPerDate: number; produceOpenCount: number; requireRegularEachShift: boolean; requireProduceOpener: boolean; noConsecutiveClose: boolean; noFullCloseAdjacent: boolean; maxConsecutiveWorkDays: number; maxWishDaysPerEmployee: number; requestDueDay: number; publishDay: number }
export type NumericOperation = Exclude<keyof Operations, 'requireRegularEachShift' | 'requireProduceOpener' | 'noConsecutiveClose' | 'noFullCloseAdjacent' | 'staffingMode'>
export type Settings = { shiftTimes: Record<'open' | 'close', Record<'regular' | 'contract', Times>> & { produceOpen: Times }; daysOffPairs: { employeeIds: number[] }[]; additionalHolidays: string[]; produceOpenExceptions: string[]; editablePastShiftDates: string[]; confirmedMonths: string[]; operations: Operations }
export type PhotoImport = { month: string; entries: { employeeId: number; date: string; code: ShiftCode }[]; notes: { id: number; date: string; text: string; resolved: boolean }[] }
export type Holiday = { date: string; name: string }
export type ScheduleOption = { id: number; shifts: { employeeId: number; date: string; code: ShiftCode }[]; warnings: string[]; optimal: boolean }
export type ScheduleHistoryItem = { id: number; month: string; username: string; action: string; createdAt: string; shiftCount: number }
export type Page = 'schedule' | 'requests' | 'employees' | 'settings'
